function createfigure(zdata1, zdata2, zdata3)
%CREATEFIGURE(zdata1, zdata2, zdata3)
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata
%  ZDATA3:  surface zdata

%  Auto-generated by MATLAB on 18-Sep-2024 18:43:46

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create mesh
mesh1 = mesh(zdata1,'Parent',subplot1);

% The following line demonstrates an alternative way to create a data tip.
% datatip(mesh1,19,1,3.23606797749979);
% Create datatip
datatip(mesh1,'DataIndex',73);

view(subplot1,[-37.5 30]);
grid(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create mesh
mesh(zdata2,'Parent',subplot2);

view(subplot2,[-37.5 30]);
grid(subplot2,'on');
hold(subplot2,'off');
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create mesh
mesh(zdata3,'Parent',subplot3);

view(subplot3,[-37.5 30]);
grid(subplot3,'on');
hold(subplot3,'off');
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create mesh
mesh(zdata1,zdata2,zdata3,'Parent',subplot4);

view(subplot4,[-37.5 30]);
grid(subplot4,'on');
hold(subplot4,'off');
